// ── 第二阶段聊天记录 ──────────────────────────────────────────────
// 在这里填写真实发生过的聊天记录
// waitForUser: true → 暂停，等用户先输入后才显示这条预设回复
//
// ── 第二阶段：真实聊天记录（由你填写）──────────────────────────────
//
// waitForUser: true  → 暂停自动播放，等用户输入后才显示这条预设回复
//                      用户的输入显示在手机右侧（手机外），预设内容在手机内
// 不带 waitForUser    → 正常自动播放
//
var CHAT_MESSAGES_2 = [
  { side: "left",  text: "刚才看到新闻，中国卫健委员会官宣，新型疫苗作为公共产品全民免费了",          delay: 800  },
  { side: "right", text: "好事",               delay: 1000, waitForUser: true },
  { side: "left",  text: "怕你逛微博看到然后发现我之前误导你，就说一下",          delay: 700 },
  { side: "left",  text: "没什么其他的事了",          delay: 700 },
  { side: "left",  text: "明天等着你醒来",          delay: 1200 },
  { side: "right", text: "我最近 沒甚麼事都不會逛微博的",          delay: 1000,  waitForUser: true },
  { side: "left",  text: "好",            delay: 700  },
  { side: "right",  text: "你快去睡",          delay: 1000,  waitForUser: true },
  { side: "left", text: "好",              delay: 900},
  { side: "left",  text: "去了",    delay: 800  },
  { side: "right",  text: "好",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "（。。。被夺舍了。。。）",    delay: 800  },
  { side: "left",  text: "最近回看了很多",    delay: 800  },
  { side: "left",  text: "我们过去的聊天",    delay: 800  },
  { side: "right",  text: "... ...",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "从一个日期但另一个日期",    delay: 800  },
  { side: "left",  text: "从一个季节到另一个季节",    delay: 800  },
  { side: "right",  text: "... ...",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "各种各样的称呼",    delay: 800  },
  { side: "left",  text: "各种各样的对话",    delay: 800  },
  { side: "left",  text: "两个遥远的脑子",    delay: 800  },
  { side: "left",  text: "两个普通的小人",    delay: 800  },
  { side: "left",  text: "你一句，我一句",    delay: 800  },
  { side: "left",  text: "像紧凑拼图一样",    delay: 800  },
  { side: "left",  text: "为彼此的生活创造了许多乐趣",    delay: 800  },
  { side: "right",  text: "噗噗",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "近几年的人生",    delay: 800  },
  { side: "left",  text: "我好像",    delay: 800  },
  { side: "left",  text: "没有方向的",    delay: 800  },
  { side: "left",  text: "随便的走着",    delay: 800  },
  { side: "left",  text: "离开了美国",    delay: 800  },
  { side: "left",  text: "离开了你",    delay: 800  },
  { side: "right",  text: "呜呜",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "看着社会的指路牌",    delay: 800  },
  { side: "left",  text: "要早点买个房子",    delay: 800  },
  { side: "left",  text: "要拿更高的工资",    delay: 800  },
  { side: "left",  text: "要做更成熟的事",    delay: 800  },
  { side: "left",  text: "要拥有的越来越多",    delay: 800  },
  { side: "left",  text: "可是我总觉得",    delay: 800  },
  { side: "left",  text: "我在拥有的越来越少",    delay: 800  },
  { side: "right",  text: "我去一下厕所",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "隔着半个地球",    delay: 800  },
  { side: "left",  text: "我们的对话",    delay: 800  },
  { side: "left",  text: "变得像是搭积木",    delay: 800  },
  { side: "left",  text: "早一块，晚一块",    delay: 800  },
  { side: "left",  text: "积木有着我们需要的实感",    delay: 800  },
  { side: "left",  text: "也少了拼图的激情",    delay: 800  },
  { side: "right",  text: "我去拿点吃的",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "工作后",    delay: 800  },
  { side: "left",  text: "我变的忙碌",    delay: 800  },
  { side: "left",  text: "聊天记录里",    delay: 800  },
  { side: "left",  text: "没有及时回复的对话越来越多",    delay: 800  },
  { side: "left",  text: "残缺上下文，像是漏风的墙",    delay: 800  },
  { side: "right",  text: "芋泥麻薯牛奶太顶胃了",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "想象你的眼睛曾在那些缝隙停留",    delay: 800  },
  { side: "left",  text: "我仿佛可以抓住一些残缺的视线",    delay: 800  },
  { side: "left",  text: "看到曾经有些时刻",    delay: 800  },
  { side: "left",  text: "三藩市的Accacia St下着雪",    delay: 800  },
  { side: "right",  text: "🐟",    delay: 1000  ,  waitForUser: true },
  { side: "right",  text: "不干嘛，手滑，你继续",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "真希望人生可以让我选择循环",    delay: 800  },
  { side: "left",  text: "从2021-03-16开始，到2026-05-29结束",    delay: 800  },
  { side: "left",  text: "完整的过完好与不好的这样的一生",    delay: 800  },
  { side: "left",  text: "然后聊天记录，忽然回到我们",    delay: 800  },
  { side: "left",  text: "第一次打电话的那一天",    delay: 800  },
  { side: "left",  text: "或者是第一次见面的那一天",    delay: 800  },
  { side: "left",  text: "又或者是第一次通过笔画猜到你的名字的那一天",    delay: 800  },
  { side: "right",  text: "你要坐着嘘嘘",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "我会说小余小余",    delay: 800  },
  { side: "right",  text: "你继续说，我可能挂电话去躺🛏。",    delay: 1000  ,  waitForUser: true },
  { side: "left",  text: "我真的好想你呀。",    delay: 800  },
];
