-- ==========================================
-- Life29 - Restaurants Table & RLS Policy
-- ==========================================
-- 在 Supabase SQL Editor 中运行此脚本

-- ==========================================
-- 1. 创建表（如果尚未创建）
-- ==========================================
-- 注意：如果表已存在，可以跳过此部分
-- 如果需要添加 type 字段到现有表，请使用下方的 ALTER TABLE 语句

/*
create table public.restaurants (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  city text null,
  rating bigint null,
  note text null,
  eat_date date null,
  "user" text null,
  type text null,
  constraint restaurants_pkey primary key (id)
) TABLESPACE pg_default;
*/

-- ==========================================
-- 2. 如果表已存在，添加 type 字段
-- ==========================================
-- 如果表已存在但没有 type 字段，运行以下语句：
-- ALTER TABLE public.restaurants ADD COLUMN IF NOT EXISTS type text null;

-- ==========================================
-- 3. 启用 RLS (Row Level Security)
-- ==========================================
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 4. 删除已有策略（如果存在）
-- ==========================================
DROP POLICY IF EXISTS "Allow public read access" ON public.restaurants;
DROP POLICY IF EXISTS "Allow public insert access" ON public.restaurants;
DROP POLICY IF EXISTS "Allow users to update own records" ON public.restaurants;
DROP POLICY IF EXISTS "Allow users to delete own records" ON public.restaurants;

-- ==========================================
-- 5. 创建 RLS 策略
-- ==========================================

-- 读取策略 - 所有人可读取所有记录
CREATE POLICY "Allow public read access"
ON public.restaurants
FOR SELECT
TO public
USING (true);

-- 插入策略 - 所有人可插入新记录
CREATE POLICY "Allow public insert access"
ON public.restaurants
FOR INSERT
TO public
WITH CHECK (true);

-- 更新策略 - 允许更新记录
CREATE POLICY "Allow users to update own records"
ON public.restaurants
FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

-- 删除策略 - 允许删除记录
CREATE POLICY "Allow users to delete own records"
ON public.restaurants
FOR DELETE
TO public
USING (true);

-- ==========================================
-- 6. 验证策略已创建
-- ==========================================
-- 运行以下查询检查策略：
-- SELECT * FROM pg_policies WHERE tablename = 'restaurants';

-- ==========================================
-- 7. 可选：创建索引提高查询性能
-- ==========================================
-- CREATE INDEX IF NOT EXISTS idx_restaurants_eat_date ON public.restaurants(eat_date DESC);
-- CREATE INDEX IF NOT EXISTS idx_restaurants_user ON public.restaurants("user");
-- CREATE INDEX IF NOT EXISTS idx_restaurants_city ON public.restaurants(city);
-- CREATE INDEX IF NOT EXISTS idx_restaurants_type ON public.restaurants(type);
-- CREATE INDEX IF NOT EXISTS idx_restaurants_rating ON public.restaurants(rating DESC);
